version: "3.8"
services:
  postgres:
    image: postgres:17.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - db-data:/var/lib/postgresql/data

  library-service:
    build:
      context: .
      dockerfile: Dockerfile.django
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
      DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
      OPAC_HOSTNAME: "${OPAC_HOSTNAME}"
      SERVICE_HOSTNAME: "${SERVICE_HOSTNAME}"
      OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
      OAUTH_CLIENT_SECRET: "${OAUTH_CLIENT_SECRET}"
      OPAC_INTERNAL_TOKEN: "${OPAC_INTERNAL_TOKEN}"
    volumes:
      - media:/app/media
      - django-static:/app/staticfiles
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        VITE_SERVICE_HOSTNAME: "${SERVICE_HOSTNAME}"
        VITE_OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
    restart: unless-stopped
    ports:
      - "${LIBRARY_PORT}:80"
    volumes:
      - media:/usr/share/nginx/html/media
      - django-static:/usr/share/nginx/html/static
    depends_on:
      - postgres
      - library-service

volumes:
  db-data:
  media:
  django-static: